# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c1e724b4eade67b09b7bf93486410f5"
name = "tensor-search"
handle = "tensor-search"
application_url = "https://faces-default-book-finding.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = ["https://faces-default-book-finding.trycloudflare.com/auth/callback", "https://faces-default-book-finding.trycloudflare.com/auth/shopify/callback", "https://faces-default-book-finding.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
